---
sudo: required
dist: focal

before_install:
    - sudo apt install -y software-properties-common
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt -qq update
    - sudo apt install -y ansible
    # search for "ansible become becoming an unprivileged user"
    # this solution was suggested on stackoverflow
    - sudo apt install -y acl

install:
  - ansible --version

script:
  # following tags conflict with pre-installed solutions on travis-ci
  # docker
  # erlang, elixir
  - ./test.sh "setup vagrant python pydata devtools"
