---


- name: install numpy linux packages
  apt: name={{ item }} state=present
  with_items:
   - libblas-dev
   - liblapack-dev

- name: install scipy linux packages
  apt: name={{ item }} state=present
  with_items:
   - gfortran 

- name: install scikit-learn linux packages
  apt: name={{ item }} state=present
  with_items:
   - libpng-dev
   - libfreetype6-dev
   - pkg-config

- name: install analysis packages into virtualenv
  pip: name={{ item }}
       virtualenv={{ venv_home }}/venv_datahacks
       state=latest
  with_items:
   - numpy
   - scipy
   - bottleneck
   - scikit-learn
   - pandas
   - seaborn
   - IPython
   - luigi

